dbConnectionString = "host=postgresql-db port=5432 user=seabug dbname=seabug password=seabug"

server.port = 9999

ogmios.address = "ogmios"
ogmios.port = 1337

blockFetcher.autoStart = true
blockFetcher.startFromLast = true
blockFetcher.firstBlock.slot = 44366242
blockFetcher.firstBlock.id = "d2a4249fe3d0607535daa26caf12a38da2233586bc51e79ed0b3a36170471bf5"
blockFetcher.filter = '''
{
    "address": "addr_test1wr05mmuhd3nvyjan9u4a7c76gj756am40qg7vuz90vnkjzczfulda"
}
'''